version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      actions-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: npm
    directory: /apps/platform-academy
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      academy-npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      api-python-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: pip
    directory: /apps/worker
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      worker-python-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      api-docker-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "python"
        versions:
          - ">= 3.13"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: docker
    directory: /apps/platform-academy
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      academy-docker-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "nginxinc/nginx-unprivileged"
        versions:
          - ">= 1.30"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: docker
    directory: /apps/worker
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      worker-docker-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "python"
        versions:
          - ">= 3.13"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      terraform-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
