apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: checkout
      namespace: payments
      jsonPointers:
        - /spec/replicas

